### ISSUE TITLE
Maintenance of installation module

### ISSUE THREAD

**Issue by clarkenj** [school-brainhack/school-brainhack.github.io#175]
## Module to maintain
Website: https://school-brainhack.github.io/modules/installation/
Code: https://github.com/school-brainhack/school-brainhack.github.io/tree/main/content/en/modules/installation

## Work to be done
Please ensure: 
- [ ] links, resources and exercises reflect the state-of-the-art 
- [ ] videos are of good quality and reflect the materials.  <br> 

If any update / re-write of the module is needed, feel free to suggest alternative material in a comment!
If you think major changes are needed, we suggest you open an issue for new modules.

**Comment by yushiangsu** [comment]
Hi, this is Yu-Shiang Su from Taiwan hub.
It seems that the installation instructions for Windows users are outdated. Microsoft has updated their [instructions](https://learn.microsoft.com/en-us/windows/wsl/install) to install WSL, and the steps are much easier now. Importantly, Docker Toolbox was deprecated, and students should install Docker Desktop which now have better support for WSL.

**Comment by complexbrains** [comment]
Dear @yushiangsu thank you for letting us know, that's amazing you caught up this. I wonder would you like to help us with updating the instructions based on new improvements please? 

All you need to do is to fork the repo and make the changes and PR, then we will review the changes accordingly. Please have a look at the [instructions for the module maintenance here](https://school-brainhack.readthedocs.io/en/latest/MODULES.html) and do not hesitate to reach us with any questions you might have.

**Comment by yushiangsu** [comment]
Yes, I glad to help. I will prepare a PR later this week.

**Comment by clarkenj** [comment]
Closing this since @yushiangsu completed a PR and I have merged

**Comment by clarkenj** [comment]
Re-opening since we decided to keep these open until modules have been 'piloted' before school starts.

**Comment by valosekj** [comment]
It seems that new macOS versions (after Monterey 12.3) dropped support for python 2.x. Details [here](https://stackoverflow.com/a/71657414).

This then results in an error when checking installation using the following command from the [Installation](https://school-brainhack.github.io/modules/installation/) module:

https://github.com/school-brainhack/school-brainhack.github.io/blob/57f93c5f21bd350a39c7cf3e895029f4033dfa81/content/en/modules/installation/index.md?plain=1#L85

Terminal output

```console
valosek@macbook-pro:~$ bash <( curl -s https://raw.githubusercontent.com/brainhackorg/school/master/content/en/modules/installation/nds_check_install.sh )
Missing software program: python. Check installation instructions
```

The proper command [here](https://github.com/school-brainhack/school-brainhack.github.io/blob/57f93c5f21bd350a39c7cf3e895029f4033dfa81/content/en/modules/installation/nds_check_install.sh#L19), in this case, should be `hash python3` instead of `hash python`: 

```console
valosek@macbook-pro:~$ hash python
hash: no such command: python
valosek@macbook-pro:~$ hash python3
```

**Comment by clarkenj** [comment]
Thanks for that @valosekj, please do let us know if you spot any other bugs!
