### ISSUE TITLE
Maintenance of introduction_to_terminal module

### ISSUE THREAD

**Issue by clarkenj** [school-brainhack/school-brainhack.github.io#176]
## Module to maintain
Website: https://school-brainhack.github.io/modules/introduction_to_terminal/
Code: https://github.com/school-brainhack/school-brainhack.github.io/tree/main/content/en/modules/introduction_to_terminal

## Work to be done
Please ensure: 
- [ ] links, resources and exercises reflect the state-of-the-art 
- [ ] videos are of good quality and reflect the materials.  <br> 

If any update / re-write of the module is needed, feel free to suggest alternative material in a comment!
If you think major changes are needed, we suggest you open an issue for new modules.

**Comment by clarkenj** [comment]
Great, thank you! Done.

**Comment by clarkenj** [comment]
Hi @chubako, how are you getting on with maintenance of this module? Do you need any help? Just a reminder that we are hoping to have these done by April 21st

**Comment by chubako** [comment]
Hi Natasha, thanks for the reminder! I'll look it up today and let you know.

Best regards!

**Comment by chubako** [comment]
Hi, I'm checking the module notes:

https://github.com/neurodatascience/course-materials-2020/blob/master/lectures/11-may/03-intro-to-shell/introduction-to-shell.ipynb
and there is a broken image at the beginning:

https://camo.githubusercontent.com/fa51703ac45f770495cfb64d3074168979ce30c19440744bb5a1069564844934/68747470733a2f2f7777772e6e6174696f6e616c67656f677261706869632e636f6d2f636f6e74656e742f64616d2f796f757273686f742f323031342f30352f333537393131332e6a7067

It's below a title that says "Why so many?! (referring to the options of
shells), so I guess it's an illustration of "many shells". Is it possible
to contact the author to update the image link? Otherwise, I think it's
best just to remove it, and if later we have time I can search for another
image.

**Comment by chubako** [comment]
Hi, I've checked the module notes and made some changes and pull requests.
Please let me know if you received them.

Regards, Alfonso.

**Comment by clarkenj** [comment]
Hi @chubako, I don't see a PR from you, can you link it here please?

**Comment by clarkenj** [comment]
Hi @chubako, I found your PRs and I realised something. We were pointing to an external repo for the jupyter book, and it does not look like it is maintained anymore. So I forked a copy to our repo so we can update it (here: https://github.com/school-brainhack/course-materials-2020). Unfortunately that means, please could you re-make your PR to this repo, so we can approve? Also, if you can make sure all the edits are in one PR that would be great. If you don't have time to do this by Monday next week then I can just fix the errors you spotted. Thank you so much!

**Comment by chubako** [comment]
Hi Natasha, no problem. I'll try to check it out tomorrow.

Best regards, Alfonso.

**Comment by chubako** [comment]
Dear Natasha, I've just sent you two pull requests. I was a little bit
confused sometimes between the old and the new repo, so I've closed few PRs
I've made, and summarized all changes in two commits:
 - one with some typos I've found
 - another to clarify some key points
Please let me know if you received the PRs, and can merge them.

Best regards, Alfonso.

**Comment by clarkenj** [comment]
Hi @chubako , I have reviewed and merged them, thank you so much!

Note, the following PRs were related to this module: 
- https://github.com/school-brainhack/course-materials-2020/pull/5
- https://github.com/school-brainhack/course-materials-2020/pull/6
- https://github.com/school-brainhack/course-materials-2020/pull/7
